--Hello, the scripts in the replicatedstorage might have some problems, i might need you guys to fix some of the scripts so it would be working, thats all - ghazali-maker
--Scripts that are not working: 1.Mailbox
--Not sure working or not: NotificationsScript.luau
--current version: Version 116
